### ISSUE TITLE
Remove unneeded javax.swing.text.html.Option import from the class com.clevercloud.biscuit.datalog.MatchedVariables

### ISSUE THREAD

**Issue by gnomix** [CleverCloud/biscuit-java#1]
- The class `com.clevercloud.biscuit.datalog.MatchedVariables` contains unneeded import `javax.swing.text.html.Option `.  This might be an issue when using Java module system for Java 9+

**Comment by Geal** [comment]
fixed in 771e02d, thanks for the report
